import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="">
      <nav className="fixed top-0 inset-x-0 h-16 md:h-20  bg-white z-10">
        <Navbar />
      </nav>
      <div className="mt-16 md:mt-20 pb-6 bg-white">
        {children}
      </div>
      <Footer/>
    </div>
  );
}
