import SideNavbar from "./components/SideNavbar";
import Navbar from "./components/Navbar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="">
      <nav className="fixed top-0 inset-x-0  h-20 shadow-md ml-64 bg-white z-10">
        <Navbar />
      </nav>
      <aside className="fixed left-0 inset-y-0 w-64 bg-white">
        <SideNavbar />
      </aside>
      <div className="mt-20 ml-64 p-6">
        {children}
      </div>
    </div>
  );
}
